# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctree < Formula
  desc "🎄 A Christmas tree right from your terminal!"
  homepage "https://github.com/gleich/ctree"
  version "1.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/ctree/releases/download/v1.0.1/ctree_1.0.1_darwin_amd64.tar.gz"
      sha256 "affff3298729504837d7bc3e63971f5a4d84d9605f5267ccca13e54b590ff887"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gleich/ctree/releases/download/v1.0.1/ctree_1.0.1_darwin_arm64.tar.gz"
      sha256 "f40f25fc5dc25dbd07d8e3274d89f9cc951520281fc0fd35fbdbe90bd2bbac16"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/ctree/releases/download/v1.0.1/ctree_1.0.1_linux_amd64.tar.gz"
      sha256 "9251e666ba361ca86d22b93885cad2f5322383bb22e78b262168670b2ebe8d81"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/ctree/releases/download/v1.0.1/ctree_1.0.1_linux_armv6.tar.gz"
      sha256 "4e9fa34267c95fbf4b217349a5fc185de73e4b2b703f3920f348261d65582333"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/ctree/releases/download/v1.0.1/ctree_1.0.1_linux_arm64.tar.gz"
      sha256 "c730a9cb8abac5f89034a590dc98506cbea316d1661f33c5d7689fda627c4ec0"
    end
  end

  def install
    bin.install "ctree"
  end
end
