# This file was generated by GoReleaser. DO NOT EDIT.
class Ctree < Formula
  desc "🎄 A Christmas tree right from your terminal!"
  homepage "https://github.com/gleich/ctree"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gleich/ctree/releases/download/v1.0.0/ctree_1.0.0_darwin_amd64.tar.gz"
    sha256 "ee7e92ff69aadf4a5c98411bf026c0251a63e5e0aabe233ca054bf6e4e15070d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/gleich/ctree/releases/download/v1.0.0/ctree_1.0.0_linux_amd64.tar.gz"
    sha256 "13277869de8f0a87fda635d169a74a1579fb69d41c3f484b3bd68823d06bc08c"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/gleich/ctree/releases/download/v1.0.0/ctree_1.0.0_linux_armv6.tar.gz"
    sha256 "2ae8593a529dee4b6d715c6ae7962aff4a746fa9ca0046938cd646ae6f08db97"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/gleich/ctree/releases/download/v1.0.0/ctree_1.0.0_linux_arm64.tar.gz"
    sha256 "2a3829efe23804783cdef1197a46627dd01439aea8bc7bdf58fcfc576372d0a1"
  end

  def install
    bin.install "ctree"
  end
end
