# This file was generated by GoReleaser. DO NOT EDIT.
class Fgh < Formula
  desc "📁 Automate the organization of your cloned GitHub repositories"
  homepage "https://github.com/Matt-Gleich/fgh"
  version "2.5.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Matt-Gleich/fgh/releases/download/v2.5.4/fgh_2.5.4_darwin_amd64.tar.gz"
    sha256 "f2269741f929ba2fb0c6a27e85e615f7fe3e48256caf7707cf7840dc20e9c081"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Matt-Gleich/fgh/releases/download/v2.5.4/fgh_2.5.4_linux_amd64.tar.gz"
    sha256 "b34bed9e19a1ac31c62999c419d7d4e8e469ef329c9dc7cef4cba7d5f5595a07"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/Matt-Gleich/fgh/releases/download/v2.5.4/fgh_2.5.4_linux_armv6.tar.gz"
    sha256 "5c0eac41982598ae11079e7bfe5eea0280a53101ef7da30b3483d86e2bc9a56e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Matt-Gleich/fgh/releases/download/v2.5.4/fgh_2.5.4_linux_arm64.tar.gz"
    sha256 "5fde606b0929d70c393e05d88f2aa609b89c2be8e8b9528d706a698f10d37ba4"
  end

  def install
    bin.install "fgh"
  end
end
