# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fgh < Formula
  desc "📁 Automate the organization of your cloned GitHub repositories"
  homepage "https://github.com/gleich/fgh"
  version "2.8.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/fgh/releases/download/v2.8.0/fgh_2.8.0_darwin_amd64.tar.gz"
      sha256 "b0b0fa646b795d507730fafda7e60da525c86b9ac50910f2244130fdc076a229"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gleich/fgh/releases/download/v2.8.0/fgh_2.8.0_darwin_arm64.tar.gz"
      sha256 "07533a56eb737211a314ca7b835dfe4cd2b52bf1209a407beacf92ff91a932d4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/fgh/releases/download/v2.8.0/fgh_2.8.0_linux_amd64.tar.gz"
      sha256 "ac6349a6bbcd1df440701b8a944301ede2bd6e72da2c348358bb7a649cd21f15"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/fgh/releases/download/v2.8.0/fgh_2.8.0_linux_armv6.tar.gz"
      sha256 "80443cf73e3e6a15b4359730f68b3e5e5f4727a107378c906c88aac139ccabcc"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/fgh/releases/download/v2.8.0/fgh_2.8.0_linux_arm64.tar.gz"
      sha256 "3b5f886bcc537c2f6c3c0b5f948156333cdf164e291dab630d063d690dbb74ea"
    end
  end

  def install
    bin.install "fgh"
  end
end
