# This file was generated by GoReleaser. DO NOT EDIT.
class LightSpeedSorting < Formula
  desc "📂 Blazing fast file sorting"
  homepage "https://mattglei.ch"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Matt-Gleich/Light-Speed-Sorting/releases/download/v1.1.0/Light-Speed-Sorting_1.1.0_darwin_amd64.tar.gz"
    sha256 "999e8f6e157dae99f9bc077f4dfef6154389d55893cf9f292d1b22ff29355793"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Matt-Gleich/Light-Speed-Sorting/releases/download/v1.1.0/Light-Speed-Sorting_1.1.0_linux_amd64.tar.gz"
      sha256 "06055f5a29dabf2667819439dbd7d25894ae2ee2ad551cbacf7b8759f988f3f3"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Matt-Gleich/Light-Speed-Sorting/releases/download/v1.1.0/Light-Speed-Sorting_1.1.0_linux_arm64.tar.gz"
        sha256 "c660e7a09f649a8229b982d196f9267188d2e5e3f0b32ca0e4646a9db8f3a788"
      else
        url "https://github.com/Matt-Gleich/Light-Speed-Sorting/releases/download/v1.1.0/Light-Speed-Sorting_1.1.0_linux_armv6.tar.gz"
        sha256 "80037bee610979f5e43bd53e3c02acf75f91ea3a222dd8ab10e31d6ef6945740"
      end
    end
  end

  def install
    bin.install "Light-Speed-Sorting"
  end
end
