# This file was generated by GoReleaser. DO NOT EDIT.
class LightSpeedSorting < Formula
  desc "📂 Blazing fast file sorting"
  homepage "https://mattglei.ch"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Matt-Gleich/light-speed-sorting/releases/download/v1.0.0/light-speed-sorting_1.0.0_darwin_amd64.tar.gz"
    sha256 "85296903c3c0c50b113a88d05b74f13507576d7adfb8c5f3c0b8b7252cac7309"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Matt-Gleich/light-speed-sorting/releases/download/v1.0.0/light-speed-sorting_1.0.0_linux_amd64.tar.gz"
      sha256 "3fab651c70899e3bef8e3602e150d1bb73fb7dce26467ed01649b852d7884641"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Matt-Gleich/light-speed-sorting/releases/download/v1.0.0/light-speed-sorting_1.0.0_linux_arm64.tar.gz"
        sha256 "5d59e980f2e0e6cde5458f30f062df31f63bbf679db338db57cd200fad010d3d"
      else
        url "https://github.com/Matt-Gleich/light-speed-sorting/releases/download/v1.0.0/light-speed-sorting_1.0.0_linux_armv6.tar.gz"
        sha256 "e1b27ac648254dab0c2de9b5c9b18c81474192e30ddbee94647bf10eafd19f1c"
      end
    end
  end

  def install
    bin.install "light-speed-sorting"
  end
end
