# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NewYearify < Formula
  desc "Update the copyright year in all of your GitHub repos "
  homepage "https://github.com/gleich/new_yearify"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/new_yearify/releases/download/v1.0.0/new_yearify_1.0.0_darwin_amd64.tar.gz"
      sha256 "f27ddb7a3bcede2df3c41f318d51af61b74737a5bec716ac096b5bb6d30c48e0"

      def install
        bin.install "new_yearify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gleich/new_yearify/releases/download/v1.0.0/new_yearify_1.0.0_darwin_arm64.tar.gz"
      sha256 "dfce21d00ffc9b8575d5199f3efa162547712963485d817271d930ac112c7039"

      def install
        bin.install "new_yearify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/new_yearify/releases/download/v1.0.0/new_yearify_1.0.0_linux_arm64.tar.gz"
      sha256 "79781cfa70ce231acc7a68a0d4de7b78579f3fedad8f44af1c35afd9b5df6980"

      def install
        bin.install "new_yearify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gleich/new_yearify/releases/download/v1.0.0/new_yearify_1.0.0_linux_amd64.tar.gz"
      sha256 "bfd1b801730878b5f9af483b36a5caea35e66a009d866d621ea491c7ccb9cb6a"

      def install
        bin.install "new_yearify"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/new_yearify/releases/download/v1.0.0/new_yearify_1.0.0_linux_armv6.tar.gz"
      sha256 "ea406daef641f6bee32801e79cedd6ed41fb859dd8e6aab06d8f30a82fe907dd"

      def install
        bin.install "new_yearify"
      end
    end
  end
end
