# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nuke < Formula
  desc "☢️ Force quit all applications with one terminal command"
  homepage "https://github.com/gleich/nuke"
  version "5.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gleich/nuke/releases/download/5.2.2/nuke_5.2.2_darwin_arm64.tar.gz"
      sha256 "068a46a8941368d4693c45d7b6fc658ac3d1c6042c7f3201323295aeedc64fd5"

      def install
        bin.install "nuke"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gleich/nuke/releases/download/5.2.2/nuke_5.2.2_darwin_amd64.tar.gz"
      sha256 "2f30bfc855c41fda499337e5480d296e0265a5eaedb38eeb048d2cf3c617135f"

      def install
        bin.install "nuke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/nuke/releases/download/5.2.2/nuke_5.2.2_linux_amd64.tar.gz"
      sha256 "9bd2085aed3bdf244f733ab8b8bc9873cb585c96868dca4dbb22ecdb7a38d200"

      def install
        bin.install "nuke"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/nuke/releases/download/5.2.2/nuke_5.2.2_linux_armv6.tar.gz"
      sha256 "ab9cfe599de1947c633d2b7d0dd726d9abde54a77731f8f06f3341d753dc6c2f"

      def install
        bin.install "nuke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/nuke/releases/download/5.2.2/nuke_5.2.2_linux_arm64.tar.gz"
      sha256 "59a3c3f99942b23370aee365fc75233e5db91402f3b817245cf377aa672dff3e"

      def install
        bin.install "nuke"
      end
    end
  end
end
