# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resin < Formula
  desc "⚗️ CLI interface for the conventional commits commit format"
  homepage "https://github.com/Matt-Gleich/resin"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/Matt-Gleich/resin/releases/download/v0.0.1/resin_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "44714aa30ead266234f4e6cb162e706181c8c286c83495e17dd9bb978a07c9be"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Matt-Gleich/resin/releases/download/v0.0.1/resin_0.0.1_Linux_x86_64.tar.gz"
    sha256 "2d2be5e7a85ba93f21ceb1ac4fb00152791b4572fbe47dcb8cf7969a3dd5d8af"
  end

  def install
    bin.install "resin"
  end
end
