# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ritcs < Formula
  desc "Quickly run terminal commands on the RIT CS machines"
  homepage "https://github.com/gleich/fgh"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/ritcs/releases/download/v0.0.1/ritcs_0.0.1_darwin_amd64.tar.gz"
      sha256 "d3e909becada1249e4041b6a419c84f1d1404a072ad07f88b58e4f50212f2eb5"

      def install
        bin.install "ritcs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gleich/ritcs/releases/download/v0.0.1/ritcs_0.0.1_darwin_arm64.tar.gz"
      sha256 "cbbcf6fad7f1b933cca6416270a758899903a2e08b23e5e1b5f06f2550c625c0"

      def install
        bin.install "ritcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gleich/ritcs/releases/download/v0.0.1/ritcs_0.0.1_linux_amd64.tar.gz"
        sha256 "83ce1cb6eac6c59d64c475d5d74f93c743d17dd2ddb33028fbd0d4f3b3d1f6ac"

        def install
          bin.install "ritcs"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/gleich/ritcs/releases/download/v0.0.1/ritcs_0.0.1_linux_armv6.tar.gz"
        sha256 "6594fb639c10ac64f3e9ec17668eda27fb9976f2c663dfaee6fdada78427eff4"

        def install
          bin.install "ritcs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gleich/ritcs/releases/download/v0.0.1/ritcs_0.0.1_linux_arm64.tar.gz"
        sha256 "11582dd1c9cd75cd5158dbfc03a1b83bca97b92c829a729083126465979ba487"

        def install
          bin.install "ritcs"
        end
      end
    end
  end
end
