# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ritcs < Formula
  desc "Quickly run terminal commands on the RIT CS machines"
  homepage "https://github.com/gleich/ritcs"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/ritcs/releases/download/v0.2.0/ritcs_0.2.0_darwin_amd64.tar.gz"
      sha256 "3b48366b0e8d0a642f6cb3efc1544c48000dd3fc270eb4b8363b4b837e1e4c7a"

      def install
        bin.install "ritcs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gleich/ritcs/releases/download/v0.2.0/ritcs_0.2.0_darwin_arm64.tar.gz"
      sha256 "e7470e5d964f8834ea8062f13c4f58ec91f6716ab158bdac992813cab77c22a3"

      def install
        bin.install "ritcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gleich/ritcs/releases/download/v0.2.0/ritcs_0.2.0_linux_amd64.tar.gz"
        sha256 "508415ca992cc1fc83edac77a80357494e834e494f4b2ff8c00c9e9fe8931677"

        def install
          bin.install "ritcs"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/gleich/ritcs/releases/download/v0.2.0/ritcs_0.2.0_linux_armv6.tar.gz"
        sha256 "354216dc6a28c61689f7b2342ec6f53a36479b603a914f20ddb1aa956d9bd219"

        def install
          bin.install "ritcs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gleich/ritcs/releases/download/v0.2.0/ritcs_0.2.0_linux_arm64.tar.gz"
        sha256 "0ccaa6da6b6d689fa6d2c66a7fcb05a05a59cdbcb4ae30b8b82cae35f45d5545"

        def install
          bin.install "ritcs"
        end
      end
    end
  end
end
