# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solar < Formula
  desc ""
  homepage "https://github.com/gleich/solar"
  version "1.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/solar/releases/download/v1.0.0/solar_1.0.0_darwin_amd64.tar.gz"
      sha256 "54b85b01108626d2adfc5b34ec73fead9f97f5242ab586b62c39ad13e1db98a2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gleich/solar/releases/download/v1.0.0/solar_1.0.0_darwin_arm64.tar.gz"
      sha256 "154b29a0739e3f403e0681916920fb4a6922d04b30333b10b6aac8d3ae75f97b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gleich/solar/releases/download/v1.0.0/solar_1.0.0_linux_amd64.tar.gz"
      sha256 "99b9054aa9f6f302ec96f265feba6f6463c4646ef3237817648fc6ef20fcf50b"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/solar/releases/download/v1.0.0/solar_1.0.0_linux_armv6.tar.gz"
      sha256 "1e4b9bc339494a456a2bdd5eed871f1452f1453cf20e55fdb48f3646c5da03e4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gleich/solar/releases/download/v1.0.0/solar_1.0.0_linux_arm64.tar.gz"
      sha256 "00f0be3236f1e8aa9bda7023734a78d578c3dcef7b86ed06f11221e993fa7264"
    end
  end

  def install
    bin.install "solar"
  end
end
