# This file was generated by GoReleaser. DO NOT EDIT.
class Texsep < Formula
  desc "Separate your pdfs from your tex files"
  homepage "https://mattglei.ch"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Matt-Gleich/texsep/releases/download/v1.0.0/texsep_1.0.0_darwin_amd64.tar.gz"
    sha256 "cef9fb6c55914d52cb475b5ad27aa474d96e6c0cdecae0611f095d7944f23732"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Matt-Gleich/texsep/releases/download/v1.0.0/texsep_1.0.0_linux_amd64.tar.gz"
      sha256 "25cb266f9d6bd70099056b33936ced3a43afec477ac901b0db5b040fb7d6d968"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Matt-Gleich/texsep/releases/download/v1.0.0/texsep_1.0.0_linux_arm64.tar.gz"
        sha256 "dd73c5931aa5ad9a1e2440cfeb53433a97233d551324b39ec24e360744c55736"
      else
        url "https://github.com/Matt-Gleich/texsep/releases/download/v1.0.0/texsep_1.0.0_linux_armv6.tar.gz"
        sha256 "4067783f2cb69140b537aedb68eada9bb6c151bc9ee279fdb9be5bfb0f57e7d4"
      end
    end
  end

  def install
    bin.install "texsep"
  end
end
